repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: ruff
        entry: poetry run ruff check . --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy src
        language: system
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        entry: poetry run bandit -r src
        language: system
        types: [python]
        pass_filenames: false
